### ISSUE TITLE
Firefix ' and / keys

### ISSUE THREAD

**Issue by nyankers** [debil03311/kip#1]
On Firefox, the `'` (け) and `/` (め) keys are used for quick find. Because you're only calling `event.preventDefault()` in the case of `Tab` being pressed, these keys are opening quick find when running the app in Firefox.

Always calling `event.preventDefault()` in `keyboardHandler()` after the `showSettings` check worked for me. You could also specifically call it if it's one of the above keys, if there's some reason you don't want to prevent default behavior otherwise.

**Comment by debil03311** [comment]
Thanks for catching this, should be fixed now! Ideally, users should be able to use as many browser shortcuts as possible, so the default behavior for the quote and slash keys will only be prevented on Firefox (at least for now). Let me know if any further issues arise.

**Comment by nyankers** [comment]
Thanks. ^^

I wasn't sure if there were many meaningful shortcuts it could prevent (it doesn't stop tab navigation, at least on Firefox), but apparently adding a bookmark (`ctrl+d`) is one of them. Doing this also writes a し, aha.

**Comment by debil03311** [comment]
Yeah same thing on chrome with the `ctrl` key but it isn't supposed to do anything in the app so I wouldn't call it an issue. Same thing for tabbing, I don't know if there are any workarounds for ff but it doesn't do anything other than toggling the debug menu so it doesn't really matter 😁
Good to know though!
